### ISSUE TITLE
default output for base quality when setting -m 1

### ISSUE THREAD

**Issue by alexander-e-f-smith** [vpc-ccg/calib#34]
Can calib deal with reads that do not have a molecular duplicate (-m 1). Currently, I'm seeing all these reads as having a default adjusted base quality of K (Q42). Is this correct behaviour? Can these reads retain original quality denotation apart from any overlap between mates where error correction could correctly be applied?

**Comment by baraaorabi** [comment]
Calib's consensus step generates three possible Q scores depending on the consensus character support in a given column in the generated multiple sequence alignment:
- `K` for >90%
- `A` for >70%
- `.` for >50%
- `$` otherwise

When you allow for non-duplicated reads (`-m 1`), their consensus will always have 100% support (out of just one read). If you want to retain the original singleton reads, I recommend running the consensus with `-m` >1, and then going back to the Calib `.cluster` file and extracting clusters with one read (all the read information is there).

Note: Calib does not correct mates of the same read together. The correction happen on each mate independently and using the other corresponding mates from the other reads that are in the same cluster.
