### ISSUE TITLE
Calib uses more than 128 GB memory on two 1.2 GB FASTQ files

### ISSUE THREAD

**Issue by rhpvorderman** [vpc-ccg/calib#47]
Hi, 

I have two 1.2 GB FASTQ (R1, R2) containing less than 3.5 million reads.

Despite the dataset being small, the tool uses more than 128GB. Because of this, I have yet to find a setting where calib runs to completion.

I currently use these settings:
```
calib --threads 1 --error-tolerance 1 --kmer-size 8 --minimizer-count 7 --minimizer-threshold 2 -f $R1_UNPACKED -r $R2_UNPACKED -o $CALIB_OUT_PREFIX -l $BARCODE_LENGTH
```
Where `BARCODE_LENGTH` is 8 in this cases. Note that these settings are the default for 150KB reads, but the error tolerance for the barcodes has been set to 1. Since there are only 65536 barcodes, all possible barcodes are used.

I am currently tweaking the settings, but I wonder if there is any advise on how to run this tool on this sort of data. Thanks!

**Comment by baraaorabi** [comment]
Calib's clustering runs in two steps. First barcodes that are at most `e` substitutions away from each other are put in separate bins. Then the reads of each of these bins are checked pairwise for their minimizers. 

Since the barcode length is too small and the all possible barcodes are used, allowing for a single error will result in all the reads to be put in the same bin. This will results in pairwise comparisons of all the reads which will take a lot of time and memory. 

This issue is arising because the barcode space is fully saturated and Calib was designed with much more sparse barcode space in mind. There are some alternative design choices that could deal efficiently with fully utilized barcode spaces (like initially clustering on the minimizers rather than the barcodes) but needs a bit of work.

**Comment by rhpvorderman** [comment]
I see. Thank you for your quick answer. Using -e 0 should then probably cluster on 65536 clusters, so that will make the comparison a bit more managable for the computer. 
Thanks!
